//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    /// Resource file `wakamizu.jpg`.
    static let wakamizuJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "wakamizu", pathExtension: "jpg")
    
    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "wakamizu", withExtension: "jpg")`
    static func wakamizuJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.wakamizuJpg
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 12 images.
  struct image {
    /// Image `bed`.
    static let bed = Rswift.ImageResource(bundle: R.hostingBundle, name: "bed")
    /// Image `callNumber`.
    static let callNumber = Rswift.ImageResource(bundle: R.hostingBundle, name: "callNumber")
    /// Image `link`.
    static let link = Rswift.ImageResource(bundle: R.hostingBundle, name: "link")
    /// Image `map`.
    static let map = Rswift.ImageResource(bundle: R.hostingBundle, name: "map")
    /// Image `marker`.
    static let marker = Rswift.ImageResource(bundle: R.hostingBundle, name: "marker")
    /// Image `money`.
    static let money = Rswift.ImageResource(bundle: R.hostingBundle, name: "money")
    /// Image `rest`.
    static let rest = Rswift.ImageResource(bundle: R.hostingBundle, name: "rest")
    /// Image `search_1xpng`.
    static let search_1xpng = Rswift.ImageResource(bundle: R.hostingBundle, name: "search_1xpng")
    /// Image `shareButton`.
    static let shareButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "shareButton")
    /// Image `stay`.
    static let stay = Rswift.ImageResource(bundle: R.hostingBundle, name: "stay")
    /// Image `train`.
    static let train = Rswift.ImageResource(bundle: R.hostingBundle, name: "train")
    /// Image `wakamizu.jpg`.
    static let wakamizuJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "wakamizu.jpg")
    
    /// `UIImage(named: "bed", bundle: ..., traitCollection: ...)`
    static func bed(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bed, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "callNumber", bundle: ..., traitCollection: ...)`
    static func callNumber(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.callNumber, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "link", bundle: ..., traitCollection: ...)`
    static func link(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.link, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "map", bundle: ..., traitCollection: ...)`
    static func map(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.map, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "marker", bundle: ..., traitCollection: ...)`
    static func marker(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.marker, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "money", bundle: ..., traitCollection: ...)`
    static func money(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.money, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "rest", bundle: ..., traitCollection: ...)`
    static func rest(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rest, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "search_1xpng", bundle: ..., traitCollection: ...)`
    static func search_1xpng(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.search_1xpng, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "shareButton", bundle: ..., traitCollection: ...)`
    static func shareButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shareButton, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "stay", bundle: ..., traitCollection: ...)`
    static func stay(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stay, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "train", bundle: ..., traitCollection: ...)`
    static func train(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.train, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "wakamizu.jpg", bundle: ..., traitCollection: ...)`
    static func wakamizuJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wakamizuJpg, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `EmptyView`.
    static let emptyView = _R.nib._EmptyView()
    /// Nib `HotelListCollectionViewCell`.
    static let hotelListCollectionViewCell = _R.nib._HotelListCollectionViewCell()
    
    /// `UINib(name: "EmptyView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.emptyView) instead")
    static func emptyView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.emptyView)
    }
    
    /// `UINib(name: "HotelListCollectionViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.hotelListCollectionViewCell) instead")
    static func hotelListCollectionViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.hotelListCollectionViewCell)
    }
    
    static func emptyView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EmptyView? {
      return R.nib.emptyView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EmptyView
    }
    
    static func hotelListCollectionViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> HotelListCollectionViewCell? {
      return R.nib.hotelListCollectionViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HotelListCollectionViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `HotelListCollectionViewCell`.
    static let hotelListCollectionViewCell: Rswift.ReuseIdentifier<HotelListCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "HotelListCollectionViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 5 storyboards.
  struct storyboard {
    /// Storyboard `Home`.
    static let home = _R.storyboard.home()
    /// Storyboard `HotelDetail`.
    static let hotelDetail = _R.storyboard.hotelDetail()
    /// Storyboard `HotelList`.
    static let hotelList = _R.storyboard.hotelList()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Search`.
    static let search = _R.storyboard.search()
    
    /// `UIStoryboard(name: "Home", bundle: ...)`
    static func home(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.home)
    }
    
    /// `UIStoryboard(name: "HotelDetail", bundle: ...)`
    static func hotelDetail(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.hotelDetail)
    }
    
    /// `UIStoryboard(name: "HotelList", bundle: ...)`
    static func hotelList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.hotelList)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Search", bundle: ...)`
    static func search(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.search)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _HotelListCollectionViewCell.validate()
    }
    
    struct _EmptyView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "EmptyView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EmptyView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EmptyView
      }
      
      fileprivate init() {}
    }
    
    struct _HotelListCollectionViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = HotelListCollectionViewCell
      
      let bundle = R.hostingBundle
      let identifier = "HotelListCollectionViewCell"
      let name = "HotelListCollectionViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> HotelListCollectionViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HotelListCollectionViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "marker", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'marker' is used in nib 'HotelListCollectionViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "train", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'train' is used in nib 'HotelListCollectionViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try home.validate()
      try hotelDetail.validate()
      try hotelList.validate()
      try launchScreen.validate()
      try search.validate()
    }
    
    struct home: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let home = StoryboardViewControllerResource<HomeController>(identifier: "Home")
      let name = "Home"
      
      func home(_: Void = ()) -> HomeController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: home)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "map", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'map' is used in storyboard 'Home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "search_1xpng", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'search_1xpng' is used in storyboard 'Home', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.home().home() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'home' could not be loaded from storyboard 'Home' as 'HomeController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct hotelDetail: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let hotelDetail = StoryboardViewControllerResource<HotelDetailViewController>(identifier: "HotelDetail")
      let name = "HotelDetail"
      
      func hotelDetail(_: Void = ()) -> HotelDetailViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: hotelDetail)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "bed", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'bed' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "callNumber", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'callNumber' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "link", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'link' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "marker", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'marker' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "rest", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'rest' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "stay", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'stay' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "train", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'train' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if UIKit.UIImage(named: "wakamizu.jpg", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'wakamizu.jpg' is used in storyboard 'HotelDetail', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.hotelDetail().hotelDetail() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'hotelDetail' could not be loaded from storyboard 'HotelDetail' as 'HotelDetailViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct hotelList: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let hotelList = StoryboardViewControllerResource<HotelListViewController>(identifier: "HotelList")
      let name = "HotelList"
      
      func hotelList(_: Void = ()) -> HotelListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: hotelList)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.hotelList().hotelList() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'hotelList' could not be loaded from storyboard 'HotelList' as 'HotelListViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct search: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Search"
      let search = StoryboardViewControllerResource<SearchViewController>(identifier: "Search")
      
      func search(_: Void = ()) -> SearchViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: search)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "search_1xpng", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'search_1xpng' is used in storyboard 'Search', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.search().search() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'search' could not be loaded from storyboard 'Search' as 'SearchViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
